### ISSUE TITLE
Remove empty Twig dir from git

### ISSUE THREAD

**Issue by monomelodies** [nickydevendt/myfirstsite#2]
Not sure how you even managed to get that in, git doesn't support directories as a concept, just files...

**Comment by nickydevendt** [comment]
Please clarify what you mean with empty directory because all the directory's I work in are containing work.
But if you mean i have multiple twig files inside the project that is true and needs cleaning and I will work on that!

If this is not what you mean please send me a message again or file another issue!

Greetings,
Nicky

**Comment by monomelodies** [comment]
![screenshot_20180327_111708](https://user-images.githubusercontent.com/260346/37958973-2e77cb70-31b2-11e8-8b5d-87104f20b7e3.png)

**Comment by nickydevendt** [comment]
Twig directory is deleted was unused anyways.

thank you!
