### ISSUE TITLE
handle errors

### ISSUE THREAD

**Issue by monomelodies** [nickydevendt/myfirstsite#4]
Default rout now points to home - should be a 404 page (with home handled explicitly in case '/')

**Comment by nickydevendt** [comment]
I made a landing page if page could not be rendered is this what you meant?

Twig render cant find the right template then land on error.html.twig

**Comment by monomelodies** [comment]
No, i meant: the default in the switch in index.php now renders home - this should render 404, whereas case '/' should render home.

**Comment by nickydevendt** [comment]
@monomelodies that was a good solution thank you I understand what you mean now and got it working but another question is it good practice to do a try and catch on each case because otherwise twig will give a very rude error. so i geuss its good to maintain that try and catch if somehow the page doesnt exist is renamed or isnt working you just get rerouted

**Comment by monomelodies** [comment]
yes, try/catch around something that MIGHT throw an exception is always a good idea!

**Comment by nickydevendt** [comment]
Thanks will do I close this subject now!
